### PR TITLE
Add global header json

### PR DESCRIPTION
**Pull request by NotNestor**
# Description

New desktop platform component for globalHeader which defines all tokens needed for global header that can be overridden for Co Branding

# Links

Screenshot 2021-09-09 at 13 47 44
Screenshot 2021-09-09 at 13 48 08

https://www.figma.com/file/7mNdbHZ2J9PjICS6Apt4we/Cobranding---DSK-%26-MOB-(Cassandra)?node-id=1296%3A7
https://www.figma.com/file/4jlvEOttJciN18b4v3GA86/ARCHIVED_Key-Screens%3A-MacOS?node-id=1501%3A1066

### CODE REVIEW

**Comment by Coread** [comment]
does this cover the global search input in the middle of the header?

**Review by jimmycoyne — APPROVED** [review]
LGTM

**Comment by NotNestor** [comment]
@Coread  yes this includes the global search textfield. I wanted to keep all the Global header tokens together as co branding allows them all to be overridden

**Comment by Coread** [comment]
> @Coread yes this includes the global search textfield. I wanted to keep all the Global header tokens together as co branding allows them all to be overridden

In which case I can't see the tokens from the with/in/from search modifier buttons.

**Comment by NotNestor** [comment]
> > @Coread yes this includes the global search textfield. I wanted to keep all the Global header tokens together as co branding allows them all to be overridden
> 
> In which case I can't see the tokens from the with/in/from search modifier buttons.

That's true, They can't be changed in co brand so didn't add them for now. You're right though i can add them

**Pull request merged**
