### PR TITLE
Add tokens for share controls that do not change colors when theme changes

### PR DESCRIPTION
**Pull request by jiaxwang**
Figma: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows%2BWeb?node-id=9532%3A17719
image
image
image

### CODE REVIEW

**Comment by paulwitty** [comment]
Two requests:
1. I'd like to ensure that these appear in Figma before adding them to the token files
2. As these are theme-independent colours, I think it would be best to separate them into a separate file theme-data/common/common.json, and then updating all of themes/theme*.json to also include that file.

**Comment by jiaxwang** [comment]
> Two requests:
> 
> 1. I'd like to ensure that these appear in Figma before adding them to the token files
> 2. As these are theme-independent colours, I think it would be best to separate them into a separate file theme-data/common/common.json, and then updating all of themes/theme*.json to also include that file.

@paulwitty These components have been added to Figma with the link above, and I have moved theme independent colors to the common.json file.

**Comment by paulwitty** [comment]
I've opened https://github.com/momentum-design/tokens/pull/80 in which I've attempted to rationalise the tokens - I couldn't see where we needed a primary and secondary button for the sharing, it looks like there's only one style of button. Please take a look at that and let me know if it looks like it covers everything, and if so I'll then push the UX team to include the additional required tokens to Figma.

**Comment by jiaxwang** [comment]
We need primary style for the "resume" button when share is stopped in the [rebrand design](https://www.figma.com/file/Qd7VK2mGCDXSX6tJ8OXYqr/Rebrand_DSK?node-id=628%3A103374), but unfortunately it is not included in the component library Figma. I've asked the UX team but they said that they are not allowed to add new tokens. If primary tokens cannot be added because they are not in the library Figma, then we are good to go with #80.

**Comment by paulwitty** [comment]
I couldn't see that resume button on the Figma at https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows%2BWeb?node-id=9532%3A17719 - it showed the sharing paused state, but not with a resume button. Is that because the Figma is not correct? Where did your image with the resume button on this PR come from?

We definitely need some new tokens for the buttons, so there will have to be some added. Let's make sure they are all the correct ones we need.

**Comment by jiaxwang** [comment]
The resume button comes from the rebrand design here: https://www.figma.com/file/Qd7VK2mGCDXSX6tJ8OXYqr/Rebrand_DSK?node-id=628%3A103374, but it is somehow not included in the component figma.

**Comment by paulwitty** [comment]
Closed in favour of #80

**Pull request closed without merging**
